services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:trixie
    command: sleep infinity
    volumes:
      - ..:/workspace:cached

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - 9090:8080
